param([switch] $Check)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$repoRoot = Split-Path $PSScriptRoot -Parent
[xml] $project = Get-Content -Raw (Join-Path $repoRoot 'src/TeeForge/TeeForge.csproj')
$version = [string] $project.Project.PropertyGroup.Version
$config = Get-Content -Raw (Join-Path $repoRoot 'docs/documentation.json') | ConvertFrom-Json
if ($version -notmatch '^\d+\.\d+\.\d+(?:-[A-Za-z0-9.-]+)?$') { throw 'Invalid package version.' }
if ($config.releaseStatus -notin @('unreleased', 'released')) { throw 'Invalid documentation release status.' }
$origin = $config.siteUrl.TrimEnd('/')
$utf8 = [System.Text.UTF8Encoding]::new($false)
$generated = [ordered]@{}
function Read-Source([string] $path) {
    return [IO.File]::ReadAllText((Join-Path $repoRoot $path)).Replace("`r`n", "`n").TrimEnd()
}
function Add-Generated([string] $path, [string] $content) {
    $generated[$path] = $content.Replace("`r`n", "`n").TrimEnd() + "`n"
}

$recipes = @(
    @{ Slug = 'copy'; File = 'CopyExample.cs'; Title = 'Copy a C# stream to multiple destinations'; Note = 'Select the extension with a destination collection; caller streams remain open and unflushed.' },
    @{ Slug = 'hash'; File = 'HashExample.cs'; Title = 'Calculate multiple hashes while copying a stream'; Note = 'Compute SHA-256 and XXH3 in one copy; access the SHA-256 result with either identifier form.' },
    @{ Slug = 'replicate'; File = 'ReplicationExample.cs'; Title = 'Replicate writes to multiple writable streams'; Note = 'Use a write-only wrapper and explicitly retain destination ownership.' },
    @{ Slug = 'broadcast'; File = 'BroadcastExample.cs'; Title = 'Broadcast a stream to independent readers'; Note = 'Start all consumers concurrently so slow-reader backpressure can make progress.' },
    @{ Slug = 'random-access'; File = 'RandomAccessExample.cs'; Title = 'Read byte ranges without changing stream Position'; Note = 'Use explicit offsets and bounded range streams with independent cursors.' }
)
$recipeLinks = [Collections.Generic.List[string]]::new()
foreach ($recipe in $recipes) {
    $source = Read-Source "samples/TeeForge.Quickstart/$($recipe.File)"
    $content = @"
# $($recipe.Title)

TeeForge $version · .NET 10 · **$($config.releaseStatus)**

$($recipe.Note)

Run from the repository root:

``````text
dotnet run --project samples/TeeForge.Quickstart -c Release -- $($recipe.Slug)
``````

The runner calls this example's RunAsync method with a cancellation token. The
example checks its result and throws on failure. Source: samples/TeeForge.Quickstart/$($recipe.File).

<!-- Generated by eng/update-docs.ps1. Edit the C# source, then regenerate. -->
``````csharp
$source
``````

[Usage guide](../agent-guide.md) · [All recipes](index.md)
"@
    Add-Generated "docs/recipes/$($recipe.Slug).md" $content
    $recipeLinks.Add("- [$($recipe.Title)]($($recipe.Slug).md): $($recipe.Note)")
}
Add-Generated 'docs/recipes/index.md' ("# TeeForge runnable C# recipes`n`nTeeForge $version · .NET 10 · **$($config.releaseStatus)**`n`n" + ($recipeLinks -join "`n"))
$hashCode = '```csharp' + "`n" + (Read-Source 'samples/TeeForge.Quickstart/HashExample.cs') + "`n" + '```'
$guide = (Read-Source 'docs/agent-guide.template.md').Replace('{{VERSION}}', $version).Replace('{{STATUS}}', $config.releaseStatus).Replace('{{HASH_EXAMPLE}}', $hashCode)
Add-Generated 'docs/agent-guide.md' $guide

$apiLines = @((Read-Source 'src/TeeForge/PublicAPI.Shipped.txt') -split "`n") +
    @((Read-Source 'src/TeeForge/PublicAPI.Unshipped.txt') -split "`n")
$removed = @($apiLines | Where-Object { $_.StartsWith('*REMOVED*') } | ForEach-Object { $_.Substring(9) })
$apiLines = @($apiLines | Where-Object { $_ -and !$_.StartsWith('#') -and !$_.StartsWith('*REMOVED*') -and $_ -notin $removed } | Sort-Object -Unique)
[Array]::Sort($apiLines, [StringComparer]::Ordinal)
$api = "# TeeForge public API reference`n`nVersion $version · **$($config.releaseStatus)** · .NET 10.`n`n" +
    "Generated from the analyzer-checked public API baseline. This is signature notation, not copyable C#: ! marks a non-null reference, ? marks a nullable reference, and -> introduces the return type. Use the [recipes](recipes/index.md) for runnable C# and the [specification](specification.md) for behavior.`n"
foreach ($feature in @('Broadcasting', 'Composition', 'ErasureCoding', 'Hashing', 'Mirroring', 'Networking', 'RandomAccess')) {
    $members = @($apiLines | Where-Object { $_ -match 'TeeForge\.([A-Za-z]+)\.' -and $Matches[1] -eq $feature })
    $api += "`n## TeeForge.$feature`n`n" + '```text' + "`n" + ($members -join "`n") + "`n" + '```' + "`n"
}
Add-Generated 'docs/api-reference.md' $api

# Current-version snapshots are refreshed together. Earlier version folders are left untouched.
$currentDocs = @($generated.Keys)
foreach ($path in $currentDocs) {
    Add-Generated ("docs/versions/$version/" + $path.Substring(5)) $generated[$path]
}
foreach ($name in @('specification.md', 'replica-stream.md', 'erasure-stream.md', 'multipath-stream.md')) {
    $sourceRef = if ($config.releaseStatus -eq 'released') { "v$version" } else { 'main' }
    $contract = (Read-Source "docs/$name").Replace('](benchmarks/README.md', "](https://github.com/DouglasCleghorn/TeeForge/blob/$sourceRef/docs/benchmarks/README.md").Replace('](../samples/', "](https://github.com/DouglasCleghorn/TeeForge/blob/$sourceRef/samples/")
    Add-Generated "docs/versions/$version/$name" $contract
}
Add-Generated "docs/versions/$version/version.json" ([ordered]@{ version = $version; status = $config.releaseStatus; framework = 'net10.0' } | ConvertTo-Json)
$index = @"
# TeeForge $version documentation

**$($config.releaseStatus)** · Requires .NET 10

Choose an API, run a complete C# example, or inspect the contracts behind it.

- [Start with the usage guide](agent-guide.md)
- [Copy, hash, replicate, broadcast, and read ranges](recipes/index.md)
- [Public API signatures](api-reference.md)
- [Behavioral specification](specification.md)
- [Replication](replica-stream.md)
- [Erasure coding](erasure-stream.md)
- [Multipath transport](multipath-stream.md)

This version is refreshed while unreleased. On publication, mark it released in
docs/documentation.json and retain its snapshot when the package version advances.
Experimental storage and mounting APIs are outside the package.
"@
Add-Generated "docs/versions/$version/index.md" $index
$llms = @"
# TeeForge

> .NET 10 library for copying streams to multiple destinations, multi-hashing,
> replication, broadcast readers and pipelines, positional I/O, erasure coding, and QUIC.

Current documented package version: $version ($($config.releaseStatus)). Match
documentation to the installed package. An unreleased version may not be on NuGet.
Both .NET HashAlgorithmName and TeeHashAlgorithm inputs use one result model.
Experimental storage and mounting tools are not part of the NuGet package.

## Start here
- [Usage guide]($origin/$version/agent-guide.md): API selection, installation, ownership, completion, and pitfalls.
- [Runnable recipes]($origin/$version/recipes/index.md): Five examples compiled and executed in CI.
- [Public API signatures]($origin/$version/api-reference.md): Exact analyzer-checked signatures grouped by namespace.
- [Documentation versions]($origin/versions.json): Available package versions and release status.

## Contracts
- [Behavioral specification]($origin/$version/specification.md): Stream capabilities, concurrency, cancellation, and failures.
- [Replication]($origin/$version/replica-stream.md): Write-only fan-out and ownership.
- [Erasure coding]($origin/$version/erasure-stream.md): Headerless geometry, member ordering, and recovery.
- [Multipath transport]($origin/$version/multipath-stream.md): Framing, completion, and control messages.

## Repository
- [Source and release history](https://github.com/DouglasCleghorn/TeeForge): Repository and version tags.
"@
Add-Generated 'llms.txt' $llms

$differences = [Collections.Generic.List[string]]::new()
foreach ($entry in $generated.GetEnumerator()) {
    $destination = Join-Path $repoRoot $entry.Key
    if (!(Test-Path -LiteralPath $destination) -or [IO.File]::ReadAllText($destination).Replace("`r`n", "`n") -cne $entry.Value) {
        if ($Check) { $differences.Add($entry.Key) }
        else {
            [IO.Directory]::CreateDirectory((Split-Path $destination -Parent)) | Out-Null
            [IO.File]::WriteAllText($destination, $entry.Value, $utf8)
        }
    }
}
if ($differences.Count) { throw "Generated documentation is stale. Run ./eng/update-docs.ps1. Files: $($differences -join ', ')" }
Write-Output "Documentation for $version is current ($($generated.Count) generated files)."
